### ISSUE TITLE
numeric task_id is not accepted and exception is hard to understand

### ISSUE THREAD

**Issue by passing** [logstash-plugins/logstash-filter-aggregate#10]
with this file in /tmp/aggregate.data:
```
{ "pid": 1, "action" : "connect",  "user" : "a" }
{ "pid": 1, "action" : "transfer" }
{ "pid": 2, "action" : "connect",  "user" : "b" }
{ "pid": 2, "action" : "transfer" }
{ "pid": 1, "action" : "disconnect" }
{ "pid": 2, "action" : "disconnect" }
```

and this configuration:
````
input {
        file {
                path => "/tmp/aggregate.data"
                type => "test"
                start_position => beginning
                sincedb_path => "/dev/null"
                codec => "json"
        }
}

filter {
        if [action] == "connect" {
                aggregate {
                        task_id => "%{pid}"
                        code => "map['user'] = event['user']"
                        map_action => "create"
                }
        }

        if [action] == "transfer" {
                aggregate {
                        task_id => "%{pid}"
                        code => "event['user'] = map['user']"
                }
        }

        if [action] == "disconnect" {
                aggregate {
                        task_id => "%{pid}"
                        code => "event['user'] = map['user']"
                        end_of_task => true
                }
        }
}

output {
        stdout {
                codec => rubydebug
        }
}
```

the filterworker throws the exception
```
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `empty?' for 1:Fixnum>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-0.1.4/lib/logstash/filters/aggregate.rb:200:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):151:in `cond_func_4'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):148:in `cond_func_4'", "(eval):93:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:error}
```

it would be nice if a number would be accepted as the task_id

workaround is possible by either adding:
```
       mutate {
           convert => [ "pid", "string" ]
       }
```

or using something like
```
   task_id => "_%{pid}"
```

**Comment by fbaligand** [comment]
Hi @passing, 

I see the problem. task_id field is thought to be a "string" object.
And when its content is composed uniquely with an integer field, the result task_id is not a string but an integer.
Later plugin calls method `task_id.empty?` which does not exist on an integer object.

I think I can fix the issue using your second trick, directly in aggregate plugin code, so that you don't have to make the trick. It allows to force the result task_id to be a string.

**Comment by fbaligand** [comment]
Hi @passing,

I can announce you that logstash-filter-aggregate has been released with your issue fixed.

If you use logstash 1.5, download logstash-filter-aggregate version 0.1.5.
If you use logstash 2.0, download logstash-filter-aggregate version 2.0.3.
