### ISSUE TITLE
Error with aggregate_maps_path

### ISSUE THREAD

**Issue by thekofimensah** [logstash-plugins/logstash-filter-aggregate#104]
I'm getting an error that I'm pretty sure has to do with the `aggregate_maps_path =>` attribute. I'm tracking the time difference between two back to back events with a given id. I start logstash with a path defined. I then pull in data until a month ago. I then stop logstash, start it again but then pull data from this month. In theory the mapping of the last timestamp from the first run should still be stored in .aggregatemaps, but upon restarting, the error below appears and the ruby code doesn't correctly do its process.

When I run without the aggregate maps path, there is no problem but the last state of the maps isn't saved.

Any ideas what is going on? I'm using LS 7.3.1.

```
[2019-10-02T12:55:20,241][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
2019-10-02 12:55:22,508 [main]>worker0 ERROR An exception occurred processing Appender plain_console java.lang.NullPointerException
	at org.logstash.ext.JrubyTimestampExtLibrary$RubyTimestamp.ruby_to_iso8601(JrubyTimestampExtLibrary.java:111)
	at org.logstash.ext.JrubyTimestampExtLibrary$RubyTimestamp.ruby_inspect(JrubyTimestampExtLibrary.java:105)
	at org.logstash.ext.JrubyTimestampExtLibrary$RubyTimestamp$INVOKER$i$0$0$ruby_inspect.call(JrubyTimestampExtLibrary$RubyTimestamp$INVOKER$i$0$0$ruby_inspect.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:139)
	at org.jruby.RubyBasicObject.rbInspect(RubyBasicObject.java:1181)
	at org.jruby.RubyObject.inspect(RubyObject.java:427)
	at org.jruby.RubyHash$4.visit(RubyHash.java:850)
	at org.jruby.RubyHash$4.visit(RubyHash.java:846)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:690)
	at org.jruby.RubyHash.visitAll(RubyHash.java:675)
	at org.jruby.RubyHash.inspectHash(RubyHash.java:841)
	at org.jruby.RubyHash.inspect(RubyHash.java:878)
	at org.jruby.RubyHash$INVOKER$i$0$0$inspect.call(RubyHash$INVOKER$i$0$0$inspect.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:139)
	at org.jruby.RubyBasicObject.rbInspect(RubyBasicObject.java:1181)
	at org.jruby.RubyObject.inspect(RubyObject.java:427)
	at org.jruby.RubyHash$4.visit(RubyHash.java:850)
	at org.jruby.RubyHash$4.visit(RubyHash.java:846)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:690)
	at org.jruby.RubyHash.visitAll(RubyHash.java:675)
	at org.jruby.RubyHash.inspectHash(RubyHash.java:841)
	at org.jruby.RubyHash.inspect(RubyHash.java:878)
	at org.jruby.RubyHash.to_s(RubyHash.java:946)
	at org.jruby.RubyHash$INVOKER$i$0$0$to_s.call(RubyHash$INVOKER$i$0$0$to_s.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
	at org.jruby.RubyObject.toRubyString(RubyObject.java:229)
	at org.jruby.RubyObject.toString(RubyObject.java:238)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.logstash.log.StructuredMessage.getFormattedMessage(StructuredMessage.java:63)
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter.format(MessagePatternConverter.java:146)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:334)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:233)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:218)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:58)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2019)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1890)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:857)
	at org.logstash.log.LoggerExt.rubyError(LoggerExt.java:103)
	at org.logstash.log.LoggerExt$INVOKER$i$0$1$rubyError.call(LoggerExt$INVOKER$i$0$1$rubyError.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:819)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:835)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_aggregate_minus_2_dot_9_dot_0.lib.logstash.filters.aggregate.RUBY$block$filter$1(/home/logstash-7.3.1/vendor/bundle/jruby/2.5.0/gems/logstash-filter-aggregate-2.9.0/lib/logstash/filters/aggregate.rb:225)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
	at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:134)
	at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:165)
	at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:177)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_aggregate_minus_2_dot_9_dot_0.lib.logstash.filters.aggregate.RUBY$method$filter$0(/home/logstash-7.3.1/vendor/bundle/jruby/2.5.0/gems/logstash-filter-aggregate-2.9.0/lib/logstash/filters/aggregate.rb:187)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_aggregate_minus_2_dot_9_dot_0.lib.logstash.filters.aggregate.RUBY$method$filter$0$__VARARGS__(/home/logstash-7.3.1/vendor/bundle/jruby/2.5.0/gems/logstash-filter-aggregate-2.9.0/lib/logstash/filters/aggregate.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/home/logstash-7.3.1/logstash-core/lib/logstash/filters/base.rb:143)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0$__VARARGS__(/home/logstash-7.3.1/logstash-core/lib/logstash/filters/base.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:177)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/home/logstash-7.3.1/logstash-core/lib/logstash/filters/base.rb:162)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1792)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/home/logstash-7.3.1/logstash-core/lib/logstash/filters/base.rb:159)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:99)
	at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:115)
	at org.logstash.generated.CompiledDataset1.compute(Unknown Source)
	at org.logstash.generated.CompiledDataset2.compute(Unknown Source)
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source)
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:425)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:292)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:28)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:90)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)
	at Users.user.home.logstash_minus_7_dot_3_dot_1.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$2(/home/logstash-7.3.1/logstash-core/lib/logstash/java_pipeline.rb:239)
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:295)
	at org.jruby.RubyProc.call(RubyProc.java:274)
	at org.jruby.RubyProc.call(RubyProc.java:270)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fbaligand** [comment]
I look at your stack trace and:
- an error happens when aggregate plugin execute your `code` for an event. 
- because of this error, aggregate plugin tries to log it, and especially to log all event data  and map data (to help you understand your code problem). 
- But when it tries to log the event data and map data, there is a null pointer exception that seems to be linked to a date object
- here the aggregate plugin line that fails: https://github.com/logstash-plugins/logstash-filter-aggregate/blob/v2.9.0/lib/logstash/filters/aggregate.rb#L225
- if you don’t reproduce it without aggregate_maps_path, maybe issue is because when maps are deserialized from aggregate_maps_path file, something is wrongly deserialized that cause later this error. 
- to understand more your initial error, I invite you to encapsulate your code section with a try/rescue block. And in the rescue block, log exception, event, but not map.

**Comment by thekofimensah** [comment]
So I figured out that the problem has to do with (as you theorized) the date field I was trying to save. It seems to have a problem with saving the @timestamp field. So I just turned all timestamps into unix ms by doing @timestamp.to_i and it seems to work.

**Comment by fbaligand** [comment]
Nice to see that you find a solution to fix your issue!
And thanks for the feedback :)
