### ISSUE TITLE
EOFError: End of file reached

### ISSUE THREAD

**Issue by duylong** [logstash-plugins/logstash-filter-aggregate#77]
Hi, 

My logstash seemed to slow for consumer, so I restarted it. When I restarted it I had an error:

```
[2017-12-06T09:18:18,165][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyMarshal.java:149:in `load'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-aggregate-2.7.0/lib/logstash/filters/aggregate.rb:134:in `block in register'", "org/jruby/RubyIO.java:1156:in `open'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-aggregate-2.7.0/lib/logstash/filters/aggregate.rb:134:in `block in register'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-aggregate-2.7.0/lib/logstash/filters/aggregate.rb:93:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:388:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:399:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:399:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:801:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:409:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:333:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:293:in `block in start'"], :thread=>"#<Thread:0x37a72b73@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290 run>"}
```

I use a large timeout and inactivity_timeout values, is there a limit for the size of the map? When I delete the map file and restarted, everything works again. Now, I reduced the value of the timeout to see.

- Version: Logstash 6.0.0
- Operating System: RHEL7
- Options: timeout => 604800 (1 week) ; inactivity_timeout => 86400 (1 week) ; push_map_as_event_on_timeout => false

**Comment by ssasporta** [comment]
I think something wrong in your logstash.conf file

Sharon Sasporta
Software Architect
Operational Architects team, GSS IP

+972-9-776-1931 (office GMT+2)
+972-52-397-2072 (mobile)
[cid:image002.jpg@01D2902F.8EF1A730]
[amdocs-a]

Follow us on Facebook<http://www.facebook.com/amdocs/>, Twitter<http://twitter.com/amdocs>, LinkedIn<http://www.linkedin.com/company/amdocs>, YouTube<http://www.youtube.com/amdocsinc>, Google+<https://plus.google.com/105657940751678445194> and the Amdocs blog network<http://blogs.amdocs.com/>.

**Comment by fbaligand** [comment]
OK, so your error stack trace says that aggregate plugin fails to load "/var/lib/logstash/aggregate.state" at startup.
So it seems that at previous shutdown, aggregate plugin failed to correctly store aggregate maps into this file.
Why ? I could only indicate some suggestions :
- maybe Logstash process has been stopped roughly while aggregate plugin was storing state into the file
- maybe there was too much maps and it fails to store them into file (I never had this case)

Anyway, so that your Logstash starts nicely, you have to delete "/var/lib/logstash/aggregate.state", because file is invalid.
Sorry, I have no better solution to suggest.

**Comment by duylong** [comment]
I did not think to look at the contents of the file, now it is deleted. I will wait to see if I have the problem again.

**Comment by fbaligand** [comment]
No answer for one month, so I close the issue.
